NAME        := simulate8086
CC          := gcc

TARGET      := $(NAME)

# -MMD and -MP will generate a simulate8086.d file alongside the executable
CFLAGS      := -Wall -Wextra -MMD -MP -g -fsanitize=address
OFLAGS      := -O3 -mpopcnt

all: $(TARGET)

$(TARGET): src/main.c
	$(CC) $(CFLAGS) $(OFLAGS) src/main.c -o $@

# Include the dependency file generated by GCC
-include $(TARGET).d

clean:
	rm -rf $(TARGET)
	rm -rf $(TARGET).d

re: clean all

.PHONY: all clean re